# This code plots discharge statistics using infilled data generated by 1_infill_and_q_50.R
# Initial code developed by SCE, 10 Jan 2023
# Updates for the Data Dashboard by Anne Marie Panetta (2026):
# Figures revised and updated


# -- SETUP -----
# clean up environment and read in needed libraries
rm(list=ls())
library(tidyverse)
library (lemon)
library (ggthemes)
library (lubridate)
library (ggplotFL)
library (ggtext)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

data_dir <- "data"
figures_dir <- "figures"

# Create figures directory if it doesn't exist
if (!dir.exists(figures_dir)) {
  dir.create(figures_dir, recursive = TRUE)
}

# read gap-filled data, created in script q_50.r
# takes a while to run so not redone here

#span control had little effect on infilling, so let's pick 7
#infilled_df <-read_csv("infilled_data/spctl_7.csv")
sp_control <- 7
infilled_df <- read_csv(file.path(data_dir, paste0("spctl_", sp_control, ".csv")))


# Calculate cumulative curves
# (ggplot(
#   infilled_df,
#   aes(x = date, y = discharge, color = is_infilled)
# ) +
#     geom_point(size = 0.01) +
#     facet_wrap(~local_site, scales = "free_y", ncol = 1) +
#     scale_x_date(date_breaks = "years") +
#     theme(axis.text.x = element_text(angle = 90))) %>%
#   ggsave(
#     file = paste0("plots/overtime_spctl_", sp_control, ".jpg"),
#     width = 8, height = 4
#   )
# 
# (ggplot(
#   infilled_df %>% filter(is_infilled == FALSE),
#   aes(x = yday, y = discharge, color = factor(year))
# ) +
#     geom_line(size = 0.01) +
#     facet_wrap(~local_site, scales = "free_y", ncol = 1) +
#     # scale_x_date(date_breaks = "years")+
#     theme(axis.text.x = element_text(angle = 90))) %>%
#   ggsave(
#     file = paste0("plots/raw_by_year.jpg"),
#     width = 8, height = 4
#   )

# for (loc in unique(infilled_df$local_site)) {
#   (ggplot(
#     infilled_df %>% filter(local_site == loc) %>%
#       mutate(yday = ifelse(wyear != year, yday - 365, yday)),
#     aes(x = yday, y = discharge, color = is_infilled)
#   ) +
#     geom_point(size = 0.01) +
#     facet_wrap(~wyear, ncol = 2) +
#     # scale_x_date(date_breaks = "years")+
#     theme(axis.text.x = element_text(angle = 90))) %>%
#     ggsave(
#       file = paste0("plots/", loc, "byyear_spctl_", sp_control, ".jpg"),
#       height = 20, width = 5
#     )
# }

wts <- infilled_df %>%
  filter(is_infilled == FALSE) %>%
  group_by(local_site, yday) %>%
  summarize(mean_daily = mean(discharge, na.rm = TRUE)) %>%
  left_join(infilled_df %>%
              filter(is_infilled == FALSE) %>%
              group_by(local_site, yday) %>%
              summarize(mean_daily = mean(discharge, na.rm = TRUE)) %>%
              filter(yday != 366) %>%
              group_by(local_site) %>%
              summarize(tot = sum(mean_daily))) %>%
  mutate(prop = mean_daily / tot) %>%
  full_join(., infilled_df)

wts <- wts %>%
  # always remove yday 366 so all yrs have same number of days
  filter(yday < 366) %>%
  # mutate(prop_this_year = prop * discharge)%>%
  group_by(local_site, wyear, is_infilled) %>%
  summarise(tot_disch = sum(prop, na.rm = TRUE)) %>%
  # summarise(tot_disch = sum(prop_this_year, na.rm=TRUE))%>%
  pivot_wider(names_from = is_infilled, values_from = tot_disch) %>%
  mutate(`TRUE` = ifelse(is.na(`TRUE`), 0, `TRUE`)) %>%
  mutate(prop_infilled = `TRUE` / (`FALSE` + `TRUE`))

# find max date by wyear
peak_flow <- infilled_df %>%
  group_by(wyear, local_site) %>%
  mutate(disch_ma_2 = slider::slide_dbl(discharge, mean,
                                        .before = 2,
                                        .after = 2
  )) %>%
  summarize(max_disch = max(disch_ma_2, na.rm = TRUE)) %>%
  full_join(infilled_df) %>%
  mutate(disch_ma_2 = slider::slide_dbl(discharge, mean,
                                        .before = 2,
                                        .after = 2
  )) %>%
  rowwise() %>%
  filter(max_disch == disch_ma_2) %>%
  filter(wyear < 2025)

# SCE- need to pull out some albion winter floods
# here, prob the 2013 floods too, and the last year
# but there is not a stron movement in the peak date,
# rather the q50 is getting earlier but not the peak

ggplot(peak_flow, aes(x = wyear, y = yday)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~local_site) +
  ggtitle("timing of peak flow")

# do q50s for these
tots <- infilled_df %>%
  # always remove yday 366 so all yrs have same number of days
  filter(yday < 366) %>%
  group_by(local_site, wyear) %>%
  summarise(
    tot_disch = sum(discharge, na.rm = TRUE),
    tot_day = sum(!is.na(discharge))
  ) %>%
  # use only complete years
  mutate(tot_disch = ifelse(tot_day != 365, NA, tot_disch)) %>%
  mutate(
    disch_50 = tot_disch / 2,
    disch_20 = tot_disch / 5,
    disch_80 = 4 * (tot_disch / 5)
  ) %>%
  left_join(., wts %>% select(local_site, wyear, prop_infilled))

avg_tots <- tots %>%
  group_by(local_site) %>%
  summarize(tot_disch = mean(tot_disch, na.rm = TRUE)) %>%
  mutate(
    disch_50_all = tot_disch / 2,
    disch_20_all = tot_disch / 5,
    disch_80_all = 4 * (tot_disch / 5)
  )

#        nday = )%>%
# cut out incomplete years by site
# mutate(tot_disch = ifelse((local_site=='mar'&(wyear>2019|wyear<1983)), NA, tot_disch))%>%
# mutate(tot_disch = ifelse((local_site=='sdl'&(wyear>2020|wyear<2000)), NA, tot_disch))%>%
# mutate(tot_disch = ifelse((wyear>2020), NA, tot_disch))%>%
# mutate(tot_disch = ifelse((wyear%in%c(2015, 2018)&local_site=='gl4'), NA, tot_disch))%>%
# mutate(tot_disch = ifelse((wyear%in%c(1981)&local_site=='alb'), NA, tot_disch))%>%
# mutate(disch_50 = tot_disch/2,
#        disch_20 = tot_disch/5,
#        disch_80 = 4*(tot_disch/5))


# plot
q50 <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_50, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q50 = min(yday), .groups = "drop") %>%
  left_join(., tots)

q50_mean <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(avg_tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_50_all, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q50_mean = min(yday), .groups = "drop")

q20 <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_20, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q20 = min(yday), .groups = "drop")

# SCE- remake these so that the q20 can be negative if it is in the fall
# (for alb etc.)

q20_mean <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(avg_tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_20_all, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q20_mean = min(yday), .groups = "drop")

q80 <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_80, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q80 = min(yday), .groups = "drop")

q80_mean <- infilled_df %>%
  # select(-tot_disch)%>%
  # left_join(., tots)%>%
  group_by(wyear, local_site) %>%
  arrange(date) %>%
  mutate(cum_discharge = cumsum(discharge)) %>%
  ungroup() %>%
  left_join(avg_tots) %>%
  rowwise() %>%
  mutate(thresh = ifelse(cum_discharge > disch_80_all, 1, 0)) %>%
  group_by(wyear, local_site) %>%
  filter(thresh == 1) %>%
  summarize(q80_mean = min(yday), .groups = "drop")

q50 <- q50 %>%
  left_join(., q20) %>%
  left_join(., q80) %>%
  left_join(., q50_mean) %>%
  left_join(., q20_mean) %>%
  left_join(., q80_mean) %>%
  mutate(duration = q80 - q20) %>%
  mutate(duration_mean = q80_mean - q20_mean)

ggplot(q50, aes(x = wyear, y = q50, color = prop_infilled)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~local_site) +
  ggtitle("q50 over time")

# are the wyears complete
cts = infilled_df%>%
  group_by(local_site, wyear) %>%
  summarize(n = dplyr::n())

# yes except albion 1981 and a few
# days of saddle in the last year after it was already 0

# make all into anomalies, by month or not
anom_disch <- infilled_df%>%
  filter(wyear >1981&wyear<2025) %>%
group_by(local_site, wyear) %>%
  summarise(
    total_disch = sum(discharge),
    ct = dplyr::n())%>%
  ungroup()%>%
  group_by(local_site) %>%
  mutate(avgdisch = mean(total_disch, na.rm = TRUE),
    anom_disch = total_disch *100/avgdisch -100,
    posneg = ifelse(anom_disch > 0, "pos", "neg") %>%
      factor(c("pos", "neg"))) %>%
  ungroup()


facet_names <-  c(alb = "Albion",
                  gl4 = "Green Lake 4",
                  mar = "Martinelli",
                  sdl = "Saddle")

row_label_sites <- c("gl4", "sdl")  # rightmost panel of each row

x_range <- range(anom_disch$wyear, na.rm = TRUE)

row_labels <- data.frame(
  local_site = row_label_sites,
  x = x_range[2] + diff(x_range) * 0.1,
  y = 0,
  label = "more~flow  %<->%  less~flow"
)

g1 <- ggplot(anom_disch , aes(x = wyear, y = anom_disch)) +
  geom_col(aes(fill = posneg)) +
  scale_fill_manual(values = c("#023E8A", "#E9A21B")) +
  labs(
    y = "Streamflow <br> (% difference from long-term mean)",
    x = "Year"
  ) +
  scale_x_continuous(
    breaks = seq(
      10 * floor(min(anom_disch$wyear) / 10),
      10 * ceiling(max(anom_disch$wyear) / 10),
      by = 10
    ),
    minor_breaks = seq(
      5 * floor(min(anom_disch$wyear) / 5),
      5 * ceiling(max(anom_disch$wyear) / 5),
      by = 5
    ),
    guide = guide_axis(minor.ticks = TRUE)
  ) +
  scale_y_symmetric() +
  geom_text(
    data = row_labels,
    aes(x = x, y = y, label = label),
    angle = -90, hjust = 0.5, vjust = 0.5, size = 2.5, inherit.aes = FALSE,
    parse = TRUE
  ) +
  theme_hc() +
  facet_wrap(~local_site, scales = 'free_y',
             labeller = as_labeller(facet_names))+
  theme(
    legend.position = "none",
    axis.minor.ticks.length = rel(0.5),
    axis.title.y = element_markdown(),
    plot.margin = margin(t = 5.5, r = 25, b = 5.5, l = 5.5)
  ) +
  coord_cartesian(xlim = x_range, clip = "off")

ggsave(g1,
       file = file.path(figures_dir, "streamflow_anom.png"),
       scale = 0.6, width = 10, height = 6
)


#### Visualizing anomalies in streamflow from Green Lake 4 by month###
# make all into anomalies, by month or not

anom_disch_month_gl4 <- infilled_df%>%
  filter(local_site == 'gl4'&wyear<2025) %>%
  mutate(month = lubridate::month(date)) %>%
  filter(month %in% c(5:9)) %>%
  group_by(wyear, month) %>%
  summarise(
    total_disch = sum(discharge))%>%
  ungroup()%>%
  group_by(month) %>%
  mutate(avgdisch = mean(total_disch, na.rm = TRUE),
         anom_disch = total_disch *100/avgdisch -100,
         posneg = ifelse(anom_disch > 0, "pos", "neg") %>%
           factor(c("pos", "neg"))) %>%
  ungroup() %>%
  mutate(month_name = 
           month(month, label=TRUE))

#Step 2: make figure
anom_disch_month_gl4 <- anom_disch_month_gl4 %>%
  mutate(month_name = factor(month_name, levels = c("May", "Jun", "Jul", "Aug", "Sep"), ordered = TRUE))

x_range_month <- range(anom_disch_month_gl4$wyear, na.rm = TRUE)

row_labels_month <- data.frame(
  month_name = factor(c("Jul", "Sep"), levels = c("May", "Jun", "Jul", "Aug", "Sep"), ordered = TRUE),
  x = x_range_month[2] + diff(x_range_month) * 0.1,
  y = 0,
  label = "more~flow  %<->%  less~flow"
)

g2 <- ggplot(anom_disch_month_gl4, aes(x = wyear, y = anom_disch)) +
  geom_col(aes(fill = posneg)) +
  scale_fill_manual(values = c("#023E8A", "#E9A21B")) +
  labs(
    y = "Streamflow <br> (% difference from long-term mean)",
    x = "Year"
  ) +
  scale_x_continuous(
    breaks = seq(
      10 * floor(min(anom_disch_month_gl4$wyear) / 10),
      10 * ceiling(max(anom_disch_month_gl4$wyear) / 10),
      by = 10
    ),
    minor_breaks = seq(
      5 * floor(min(anom_disch_month_gl4$wyear) / 5),
      5 * ceiling(max(anom_disch_month_gl4$wyear) / 5),
      by = 5
    ),
    guide = guide_axis(minor.ticks = TRUE)
  ) +
  scale_y_symmetric() +
  geom_text(
    data = row_labels_month,
    aes(x = x, y = y, label = label),
    angle = -90, hjust = 0.5, vjust = 0.5, size = 3.5, inherit.aes = FALSE,
    parse = TRUE
  ) +
  theme_hc() +
  facet_wrap(~month_name, nrow = 2, ncol = 3, axes = "all") +
  theme(
    legend.position = "none",
    axis.minor.ticks.length = rel(0.5),
    axis.title.y = element_markdown(),
    plot.margin = margin(t = 5.5, r = 25, b = 5.5, l = 5.5)
  ) +
  coord_cartesian(xlim = x_range_month, clip = "off")

ggsave(g2,
       file = file.path(figures_dir, "streamflow_anom_gl4_month.png"),
       scale = 0.7, width = 10, height = 7
)

###Visualizing daily streamflow in Green Lake 4 relative to historical pattern###
summer_disch_last_yr <- infilled_df%>%
  filter(local_site == 'gl4'&wyear<2025) %>%
  mutate(month = lubridate::month(date)) %>%
  filter(month %in% c(5:9)) %>%
  mutate(yday = lubridate::yday(date)) %>%
  filter(wyear == 2024) %>%
  left_join(infilled_df%>%
              filter(local_site == 'gl4'&wyear<2025) %>%
              mutate(yday = lubridate::yday(date),
                     month = lubridate::month(date)) %>%
              filter(month %in% c(5:9)) %>%
              filter(wyear != 2024) %>%
              select(yday, discharge) %>%
              rename(oth = discharge))

# Use historical data to build the quantile ribbon
hist_data_disch <- infilled_df %>%
  filter(local_site == 'gl4' & wyear < 2025 & wyear != 2024)

fill_legend_disch <- paste0(
  "10th-90th percentile \n", "(",
  min(hist_data_disch$wyear), "-",
  max(hist_data_disch$wyear), ")"
)

g3 <- ggplot(summer_disch_last_yr %>%
               ungroup(), aes(x = date)) +
  geom_flquantiles(aes(y = oth),
                   probs = c(0.10, 0.90), fill = "#4C72B0", alpha = 0.25,
                   na.rm = TRUE
  ) +
  # invisible dummy layer, included to create the fill legend swatch
  geom_ribbon(
    data = summer_disch_last_yr %>% ungroup() %>% slice(1),
    aes(x = date, ymin = discharge, ymax = discharge, fill = fill_legend_disch),
    alpha = 0.25
  ) +
  geom_line(aes(y = discharge, color = as.character(wyear))) +
  scale_fill_manual(
    name = NULL,
    values = setNames("#4C72B0", fill_legend_disch)
  ) +
  scale_color_manual(
    name = NULL,
    values = setNames("black", as.character(unique(summer_disch_last_yr$wyear)))
  ) +
  ylab("Streamflow (cubic meters)") +
  theme_hc() +
  labs(
    title = "Green Lake 4 Summer Streamflow",
    subtitle = "Daily discharge vs. historical range"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    plot.subtitle = element_text(size = 10, color = "grey40", hjust = 0.5)
  )

ggsave(g3,
       file = file.path(figures_dir, "streamflow_summer_gl4_2024.png"),
       scale = 0.6, width = 8, height = 6
)
